AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - 'vendor/'
    - '*.spec'
    - 'Rakefile'
  NewCops: enable

# Don't enforce documentation
Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Max: 60

Metrics/ClassLength:
  Max: 400

Metrics/MethodLength:
  Max: 60

Metrics/LineLength:
  Max: 190

Style/SingleLineMethods:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false
